/** Mismos colores y tipografías del panel admin, para que se sienta el mismo sistema. */
export default {
  content: ['./web/index.html', './web/src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#012d1d',
        'on-primary': '#ffffff',
        'primary-fixed': '#c1ecd4',
        'primary-fixed-dim': '#a5d0b9',
        'on-primary-fixed': '#002114',
        'on-primary-fixed-variant': '#274e3d',
        'primary-container': '#1b4332',
        'on-primary-container': '#86af99',
        secondary: '#7b5819',
        'on-secondary': '#ffffff',
        'secondary-fixed': '#ffdeae',
        'secondary-fixed-dim': '#eebf76',
        'on-secondary-fixed': '#281900',
        'secondary-container': '#fdcd83',
        'on-secondary-container': '#785516',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#fcf9f4',
        surface: '#fcf9f4',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3ee',
        'surface-container': '#f0ede8',
        'surface-container-high': '#ebe8e3',
        'surface-variant': '#e5e2dd',
        'on-surface': '#1c1c19',
        'on-surface-variant': '#414844',
        outline: '#717973',
        'outline-variant': '#c1c8c2',
        'inverse-surface': '#31302d',
        'inverse-on-surface': '#f3f0eb',
      },
      borderRadius: { DEFAULT: '0.25rem', lg: '0.5rem', xl: '0.75rem', '2xl': '1rem', full: '9999px' },
      fontFamily: {
        headline: ['Newsreader', 'Georgia', 'serif'],
        body: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        label: ['Inter', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
